version: '2'

services:
#  app:
#    image: 'bdip-ticketing-server-main:latest'
#    build:
#      context: .
#    container_name: app
#    ports:
#      - "8007:8007"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ticketing
      - POSTGRES_PASSWORD=ticketing-password-local
      - POSTGRES_DB=testdb