server:
  port: 8007
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      discovery:
        enabled: true
      exposure:
        include: health,info,conditions,env
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    conditions:
      enabled: true
    env:
      enabled: true
  info:
    java:
      enabled: true
    env:
      enabled: true
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  .h2:
    console.enabled: true
  data:
    rest:
      enable-enum-translation: true
logging:
  level:
    root: WARN
    com.ridebeep.bdipticketingserver: INFO