server:
  port: 8007
  error.include-message: always
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      discovery:
        enabled: true
      exposure:
        include: health,info,conditions,env
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    conditions:
      enabled: true
    env:
      enabled: true
  info:
    java:
      enabled: true
    env:
      enabled: true
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: tickets
    password: tickets-password-local
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-description: 'Initial'
    baseline-on-migrate: true
  data:
    rest:
      enable-enum-translation: true
logging:
  level:
    root: WARN
    com.ridebeep.bdipticketserver: INFO